In [1]:
# ########################################################## #
#                                                            #
# Name: KEV:Constant Evaluator                               #
# Author: GGamov                                             #
# Date: 2019                                                 #
#                                                            #
# ########################################################## #

# import libraries -------------------------------------------

import pandas as pd
from openpyxl import load_workbook
import re
import io
import os
import pdb

import sys
sys.path.append(os.path.abspath('../kev/'))

import eq_data
import eq_preproc
import eq_evaluator
import eq_postproc
import eq_writer


# basic input ------------------------------------------------
 
def cl_scripts_load(_sep, _subdir, _file):
    
    # if specific file selected it should be XLSX one
    if _file != "":
        
        if _subdir != '':
            _subdir = '/' + _subdir
        _subdir = '../../input' + _subdir + '/'

        _file = _subdir + _file
        
        # open excel file
        with open(_file, "rb") as f:
            inmemory_file = io.BytesIO(f.read())
        wb = load_workbook(inmemory_file, read_only = True)
                
        r = re.compile(r'heats')
        heats_data = pd.read_excel(_file, sheet_name = list(filter(r.search, wb.sheetnames))[0], index_col = 0)
        
        r = re.compile(r'targets')
        targets = pd.read_excel(_file, sheet_name = list(filter(r.search, wb.sheetnames))[0], header = None)
        
        r = re.compile(r'enthalpies')
        delta_H = pd.read_excel(_file, sheet_name = list(filter(r.search, wb.sheetnames))[0])
        
    # use a bunch of plain text files instead
    else:
          
        if _subdir != '':
            _subdir = '/' + _subdir
        _subdir = '../../input' + _subdir + '/'

        file_names = list(os.listdir(path = _subdir))

        r = re.compile(r'heats')
        file = list(filter(r.search, file_names))[0]
        file = _subdir + str(file)
        heats_data = pd.read_csv(file, sep = _sep, decimal = ",", index_col = 0)
        
        r = re.compile(r'targets')
        file = list(filter(r.search, file_names))[0]
        file = _subdir + str(file)
        targets = pd.read_csv(file, sep = _sep, header = None)
        
        r = re.compile(r'enthalpies')
        file = list(filter(r.search, file_names))[0]
        file = _subdir + str(file)
        delta_H = pd.read_csv(file, sep = _sep)
        
    return heats_data, targets, delta_H

In [2]:
# ########################################################## #
#                                                            #
# Name: KEV:Constant Evaluator                               #
# Author: GGamov                                             #
# Date: 2019                                                 #
#                                                            #
# ########################################################## #

# import libraries -------------------------------------------

import numpy as np
import re

# basic preprocessing ----------------------------------------
    
def cl_preproc(con_data, prod_names, idx, type_con, heats_data, targets, delta_H, _calor_setup_type):
    
    # checking if there are several series
    
    if 'series' not in con_data.columns:        
        con_data['series'] = ''
    
    if 'series' not in heats_data.index:
        heats_data.loc['series'] = '' # probably not needed
    
    if 'volumes' not in heats_data.index:
        heats_data.loc['volumes'] = 1        

    # series variables
    
    ser_info = con_data['series'].to_numpy()
    ser_unique = np.unique(ser_info)
    ser_num = np.shape(np.unique(ser_info))[0]
    
    ser_counts = con_data.groupby(['series']).size().tolist();
    
    # reading volumes from experimental data
    volumes = heats_data.loc['volumes'].to_numpy()
    
    # reading exp heats from experimental data
    heats = heats_data.loc['observation'].to_numpy() - heats_data.loc['dilution'].to_numpy()
        
    # transforming deviation to the matrix form
    devs = heats_data.loc['deviation'].to_numpy()
    devs = np.diag((1 / (np.array(devs) * np.array(devs))) * (np.sum(np.array(devs) * np.array(devs)) / len(devs)))
    
    # creating vector of known enthalpies
    dH_par = np.hstack((np.zeros(len(prod_names_con)), np.transpose(delta_H.drop('Reaction', axis = 1).to_numpy())[0]))
    
    # number of constant to find
    tar_names = set(targets.to_numpy()[0][1:])
    tar_num = [index for index, item in enumerate(prod_names) if item in tar_names]
    
    # number of enthalpy to find
    dH_names = np.hstack((prod_names_con, np.transpose(delta_H.drop('Value', axis = 1).to_numpy())[0]))
    un_el = set(prod_names) - set(dH_names)
    dH_ind_wtf = list([index for index, item in enumerate(prod_names) if item in un_el])
    un_el = set(prod_names) - (set(prod_names) - set(dH_names))
    dH_ind = list([index for index, item in enumerate(prod_names) if item in un_el])
    
    # creating array of diff total concentrations
    con_matrix_red = []
    for s in range(ser_num):
        for k in range(ser_counts[s] - 1):
            con_matrix_red.append(con_matrix[int(np.sum(ser_counts[:s])) + k + 1])
            
    if _calor_setup_type == 'DSC' or 'overfilled':
        _calor_setup_type_coeff = [[1] for i in range(len(con_matrix_red))]
    
    if _calor_setup_type == 'ampoule':
        _calor_setup_type_coeff = 1 / np.array(con_matrix_red)[:, idx] 
    
    return (ser_num, ser_counts, ser_info, volumes, heats, devs, tar_num, dH_ind, dH_ind_wtf, dH_par, 
            _calor_setup_type_coeff)

In [3]:
# ########################################################## #
#                                                            #
# Name: KEV:Constant Evaluator                               #
# Author: GGamov                                             #
# Date: 2019                                                 #
#                                                            #
# ########################################################## #

# import libraries -------------------------------------------

import numpy as np

def cl_enthalpies(ser_num, ser_counts, c_res_out, devs, volumes, heats, dH_ind, dH_par, dH_ind_wtf, _calor_setup_type_coeff, _calor_setup_type):

    # finding the increment in equilibrium concentrations of products - needed for dH calculation
    vol_active = 0.988 # terrible solution. Gotta introduce new variable for operating volume 
    vol_init = 15      # of calorimetric cell for overfilled mode
    dif_conc = []        
             
    for s in range(ser_num):    
        for k in range(ser_counts[s] - 1):
            
            if _calor_setup_type == 'overfilled':
                factor = 1 - (volumes[int(np.sum(ser_counts[:s])) + k - s] / vol_active)
            else:
                factor = 1
            
            dif_conc.append(c_res_out[int(np.sum(ser_counts[:s])) + k + 1] - c_res_out[int(np.sum(ser_counts[:s])) +
                                                                                       k] * factor)
            
    dif_conc, devs, volumes = np.array(dif_conc).astype(np.float32), devs.astype(np.float32), volumes.astype(np.float32)
    
    dif_vol = np.diff(volumes)
    dif_vol = np.array(np.hstack((volumes[0] - vol_init, dif_vol)))
    
    # finding vector of experimental values
    
    q_corr = deepcopy(heats)
    
    for i in range(len(heats)):
        for j in range(len(volumes[dH_ind])):
            
            if _calor_setup_type == 'overfilled':
                q_corr[i] -= vol_active * dif_conc[i, dH_ind[j]] * dH_par[j] 
            else:
                q_corr[i] -= (volumes[dH_ind[j]] * dif_conc[i, dH_ind[j]] * dH_par[j] +
                              dif_vol[i] * np.array(c_res_out)[i, dH_ind[j]] * dH_par[j])
    
    if _calor_setup_type == 'overfilled' or _calor_setup_type == 'DSC':
        c_eq = []
        for s in range(ser_num):
            for k in range(ser_counts[s] - 1):
                c_eq.append(c_res_out[int(np.sum(ser_counts[:s])) + k])
    else:
        c_eq = dif_conc
    
    if _calor_setup_type == 'overfilled':
        A = (vol_active * dif_conc[:, dH_ind_wtf]) * np.array(_calor_setup_type_coeff)
    
    else:
        A = ((np.array(volumes).reshape((len(volumes), 1)) * dif_conc[:, dH_ind_wtf]) * np.array(_calor_setup_type_coeff) +
             dif_vol.reshape((len(dif_vol), 1)) * np.array(c_eq)[:, dH_ind_wtf])
    
    AT = np.transpose(A)
    LTP = np.linalg.inv(np.dot(np.dot(AT, devs), A))
    RTP = np.dot(np.dot(AT, devs), q_corr)
    dH_res = np.dot(LTP, RTP)
    dH_res_tmp = dH_par

    for i in range(len(dH_ind_wtf)):
        dH_res_tmp = np.insert(dH_res_tmp, dH_ind_wtf[i], dH_res[i])

    dH_res_out = dH_res_tmp

    F_min, heats_calc = 0, []
    
    for i in range(len(heats)): 
        
        if _calor_setup_type == 'overfilled':
            F_min += (vol_active * np.sum(dH_res_out * dif_conc[i] * np.array(_calor_setup_type_coeff[i])) - heats[i]) ** 2
            
            heats_calc.append((np.sum(dH_res_out * dif_conc[i] * vol_active * _calor_setup_type_coeff[i])))
        
        else:
            F_min += ((np.sum(dH_res_out * dif_conc[i] * volumes[i] * np.array(_calor_setup_type_coeff[i])) +
                       np.sum(dH_res_out * c_eq[i] * dif_vol[i]) - heats[i]) ** 2)
            
            heats_calc.append(np.sum(dH_res_out * dif_conc[i] * volumes[i] * np.array(_calor_setup_type_coeff[i]))
                              + np.sum(dH_res_out * c_eq[i] * dif_vol[i]))
    print('\neq con')
    print(np.array(c_res_out))
    print('\ndif con')
    print(dif_conc)
    print('\nvol')
    print(volumes)
    print('\ndH par')
    print(dH_par)
    print('\nsum of terms')
    print(np.array(heats_calc))
    print(heats)
    
    #print(sum(heats))
    #print(dH_res_out)
    #print(np.sum(dif_conc[i]))
    #print(np.sum(volumes[i]))
    #print(np.sum(np.array(_calor_setup_type_coeff[i])))
    
    # calculating st. dev. of dH_res / checking the quality of linear regression
    # consider making it in separate function
    
    disp = (F_min / (len(heats) - len(dH_ind_wtf)) * (np.diag(LTP))) ** 0.5  
    
    return F_min, dH_res_out, disp

In [4]:
# ########################################################## #
#                                                            #
# Name: KEV:Constant Evaluator                               #
# Author: GGamov                                             #
# Date: 2019                                                 #
#                                                            #
# ########################################################## #

# import libraries -------------------------------------------

from copy import deepcopy
import eq_evaluator
# import also script cl_enthalpies when needed

# main Hooke-Jeeves procedure --------------------------------
def cl_hooke_jeeves(F_min, tar_num, lg_k, step_init, max_iter, eps, ser_num, st_coeff_matrix, type_con,
        con_matrix, ign_indices, ser_counts, ser_info, devs, volumes, heats, dH_ind, dH_par, dH_ind_wtf, 
                _calor_setup_type_coeff, _calor_setup_type):

    basis_point, lg_k, new_min, c_res_out, disp = cl_exploratory(F_min, tar_num, lg_k, step_init, max_iter, eps, ser_num, st_coeff_matrix, type_con,
        con_matrix, ign_indices, ser_counts, ser_info, devs, volumes, heats, dH_ind, dH_par, dH_ind_wtf, 
                _calor_setup_type_coeff, _calor_setup_type)
    print(new_min)

    for i in range(max_iter):
        print('\niteration', i, lg_k[tar_num])
        if F_min <= new_min:
        
            if step_init < HJ_eps:
                print("p1 " + str(step_init) + " " + str(HJ_eps))
                break
            
            else: 
                 
                step_init /= 2
            
                basis_point, lg_k, new_min, c_res_out, disp = cl_exploratory(F_min, tar_num, lg_k, step_init, max_iter, eps, ser_num,
                                  st_coeff_matrix, type_con, con_matrix, ign_indices, ser_counts, ser_info, devs,
                                  volumes, heats, dH_ind, dH_par, dH_ind_wtf, _calor_setup_type_coeff, _calor_setup_type)
                print('\nF min more ', new_min, F_min, lg_k[tar_num])
                print(str(step_init))
        else:
            F_min = deepcopy(new_min)
            print('\nF min less', new_min, F_min, lg_k[tar_num])
            print(str(step_init))
            basis_point_n = deepcopy(lg_k)
            lg_k[tar_num] = basis_point[tar_num] + 2 * (lg_k[tar_num] - basis_point[tar_num])

            c_res_out, g_res_out = eq_evaluator.eq_calc(max_iter, eps, st_coeff_matrix, type_con, lg_k,
                                                    con_matrix, ign_indices)

            new_min, dH_res_out, disp = cl_enthalpies(ser_num, ser_counts, c_res_out, devs, volumes, heats
                                          , dH_ind, dH_par, dH_ind_wtf, _calor_setup_type_coeff, _calor_setup_type)
            print('\nF min less after', new_min, F_min, lg_k[tar_num])
        
            if F_min <= new_min:
                lg_k = deepcopy(basis_point_n)
                print('\nconstant less after', basis_point[tar_num], lg_k[tar_num]) 
            else:
                F_min = new_min

            basis_point, lg_k, new_min, c_res_out, disp = cl_exploratory(F_min, tar_num, lg_k, step_init, max_iter, eps, ser_num,
                                  st_coeff_matrix, type_con, con_matrix, ign_indices, ser_counts, ser_info, devs,
                                  volumes, heats, dH_ind, dH_par, dH_ind_wtf, _calor_setup_type_coeff, _calor_setup_type)
        
            if F_min <= new_min:
            
                print('\nF min p2', new_min, F_min, lg_k[tar_num])
                if step_init < HJ_eps:
                    print("p2")
                    break
            
                else: 
                
                    step_init /= 2
        
            else:

                F_min = deepcopy(new_min)
            
                print('\nF min p3.1', new_min, F_min, lg_k[tar_num])
            
                basis_point_n = deepcopy(lg_k)
                lg_k[tar_num] = basis_point[tar_num] + 2 * (lg_k[tar_num] - basis_point[tar_num])
            
                c_res_out, g_res_out = eq_evaluator.eq_calc(max_iter, eps, st_coeff_matrix, type_con, lg_k,
                                                        con_matrix, ign_indices)
    
                new_min, dH_res_out, disp = cl_enthalpies(ser_num, ser_counts, c_res_out, devs, volumes, heats
                                              , dH_ind, dH_par, dH_ind_wtf, _calor_setup_type_coeff, _calor_setup_type)
        
                if F_min <= new_min:
                    lg_k = deepcopy(basis_point_n)
            
                print('\nF min p3.2', new_min, F_min, lg_k[tar_num])
    
    return F_min, lg_k, dH_res_out, c_res_out, disp

# exploratory move function used in main function ------------------------
def cl_exploratory(F_min, tar_num, lg_k, step_init, max_iter, eps, ser_num, st_coeff_matrix, type_con,
        con_matrix, ign_indices, ser_counts, ser_info, devs, volumes, heats, dH_ind, dH_par, dH_ind_wtf, 
                _calor_setup_type_coeff, _calor_setup_type):

    basis_point = deepcopy(lg_k)
    
    c_res_out, g_res_out = eq_evaluator.eq_calc(max_iter, eps, st_coeff_matrix, type_con, lg_k, 
                                                con_matrix, ign_indices)

    new_min, dH_res_out, disp = cl_enthalpies(ser_num, ser_counts, c_res_out, devs, volumes, heats
                                          , dH_ind, dH_par, dH_ind_wtf, _calor_setup_type_coeff, _calor_setup_type)

    #if F_min > new_min:
    F_min = new_min
    
    for j in range(len(tar_num)): 
        #pdb.set_trace()
        print('input', lg_k[tar_num[j]], F_min)
        
        lg_k[tar_num[j]] = lg_k[tar_num[j]] + step_init
        
        c_res_out, g_res_out = eq_evaluator.eq_calc(max_iter, eps, st_coeff_matrix, type_con, lg_k,
            con_matrix, ign_indices)
        #print('\na1 ', new_min, F_min)
        new_min, dH_res_out, disp = cl_enthalpies(ser_num, ser_counts, c_res_out, devs, volumes, heats, dH_ind, dH_par, dH_ind_wtf, 
                                   _calor_setup_type_coeff, _calor_setup_type)
        print('right', lg_k[tar_num[j]], new_min, F_min)
        #print('\na2 ', new_min, F_min)
        if F_min <= new_min:
            
            lg_k[tar_num[j]] = lg_k[tar_num[j]] - 2 * step_init
            
            c_res_out, g_res_out = eq_evaluator.eq_calc(max_iter, eps, st_coeff_matrix, type_con, lg_k, 
                                                        con_matrix, ign_indices)
        
            new_min, dH_res_out, disp = cl_enthalpies(ser_num, ser_counts, c_res_out, devs, volumes, heats
                                                  , dH_ind, dH_par, dH_ind_wtf, _calor_setup_type_coeff, _calor_setup_type)
            print('left', lg_k[tar_num[j]], new_min, F_min)
            #print('\na3 ', new_min, F_min)
            if F_min <= new_min:
                
                lg_k[tar_num[j]] = lg_k[tar_num[j]] + step_init
                new_min = deepcopy(F_min)
                #print('\na4 ', new_min, F_min)
            #else:
                
                #new_min = deepcopy(F_min)
                
        #else:
            
            #new_min = deepcopy(F_min)
    print('return', basis_point[tar_num[j]], lg_k[tar_num[j]])
    #print('\na5 ', new_min, F_min)
    return basis_point, lg_k, new_min, c_res_out, disp

In [5]:
# ########################################################## #
#                                                            #
# Name: KEV:Constant Evaluator                               #
# Author: GGamov                                             #
# Date: 2019                                                 #
#                                                            #
# ########################################################## #

# import libraries -------------------------------------------
import numpy as np
import eq_evaluator
# import also script cl_enthalpies when needed

def cl_constants_errs(lg_k, heats, tar_num, HJ_eps, max_iter, eps, st_coeff_matrix, type_con, con_matrix,
                      ign_indices, ser_num, ser_counts, devs, volumes, dH_ind, dH_par, dH_ind_wtf, 
                      _calor_setup_type_coeff, _calor_setup_type):
    
    # creating constants vectors ---------------------------------
    lg_k_1, lg_k_2 = np.array(lg_k), np.array(lg_k)
    heats_one, heats_two = [0] * len(heats), [0] * len(heats)
    jc_mtrx = [[0] * len(heats) for i in range(len(tar_num))]

    for i in range(len(tar_num)):
        # calculating the heats for Jacobi matrix computing
        lg_k_1[tar_num[i]] += HJ_eps
        lg_k_2[tar_num[i]] -= HJ_eps
    
        # if lg_k is overestimated
        c_res_out_dist, g_res_out = eq_evaluator.eq_calc(max_iter, eps, st_coeff_matrix, type_con, lg_k_1,
                                                        con_matrix, ign_indices)
    
        new_min, dH_res_out_dist, disp = cl_enthalpies(ser_num, ser_counts, c_res_out, devs, volumes, heats, dH_ind, dH_par, dH_ind_wtf, 
                                                       _calor_setup_type_coeff, _calor_setup_type)
    
        dif_conc = [] 
        for s in range(ser_num):    
            for k in range(ser_counts[s] - 1):
                dif_conc.append(c_res_out_dist[int(np.sum(ser_counts[:s])) + k + 1] - c_res_out_dist[int(np.sum(ser_counts[:s])) + k])
    
        for o in range(len(heats)):
            heats_one[o] = np.sum(dif_conc[o] * dH_res_out_dist) * volumes[o]
    
        # if lg_k is underestimated    
        c_res_out_dist, g_res_out = eq_evaluator.eq_calc(max_iter, eps, st_coeff_matrix, type_con, lg_k_2,
                                                        con_matrix, ign_indices)
    
        new_min, dH_res_out_dist, disp = cl_enthalpies(ser_num, ser_counts, c_res_out, devs, volumes, heats, dH_ind, dH_par, dH_ind_wtf, 
                                                       _calor_setup_type_coeff, _calor_setup_type)
    
        dif_conc = [] 
        for s in range(ser_num):    
            for k in range(ser_counts[s] - 1):
                dif_conc.append(c_res_out_dist[int(np.sum(ser_counts[:s])) + k + 1] - c_res_out_dist[int(np.sum(ser_counts[:s])) + k])    
   
        for o in range(len(heats)):
            heats_two[o] = np.sum(dif_conc[o] * dH_res_out_dist) * volumes[o]
    
        # calculating the Jacobi matrix    
        jc_mtrx[i] = (np.array(heats_one) - np.array(heats_two)) / (2 * HJ_eps)

        jc_mtrx, devs = np.array(jc_mtrx).astype(np.float32), devs.astype(np.float32)

    cov_matrix = (F_min / (len(heats) - len(tar_num))) * np.linalg.inv(np.dot(np.dot(jc_mtrx, devs), np.transpose(jc_mtrx)))

    errs_values = np.diag(cov_matrix) ** 0.5
    return errs_values

In [6]:
# input for xlsx file
_subdir = "calorimetry"
_sep = ";"
_file = "test_6.xlsx"
_calor_setup_type = 'DSC' # use 'DSC' for test_1, test_2 and test_5; use 'ampoule' for test_3; use 'overfilled' for test_4

max_iter, eps, HJ_eps, step_init = 100, 0.0000001, 0.0001, 0.5

# load data

st_coeff_data, lg_k_data, con_data, type_con, component_name_for_yields = eq_data.eq_scripts_load(_sep, _subdir, _file)
heats_data, targets, delta_H = cl_scripts_load(_sep, _subdir, _file)

# preproc

st_coeff_matrix, prod_names, lg_k, prod_names_con, con_matrix, ign_indices, idx, type_con = eq_preproc.eq_preproc(
    st_coeff_data, con_data, type_con, lg_k_data, component_name_for_yields)

(ser_num, ser_counts, ser_info, volumes, heats, devs, 
 tar_num, dH_ind, dH_ind_wtf, dH_par, _calor_setup_type_coeff) = cl_preproc(
    con_data, prod_names, idx, type_con, heats_data, targets, delta_H, _calor_setup_type)

# calculation of eq concentration (starting point)
c_res_out, g_res_out = eq_evaluator.eq_calc(max_iter, eps, st_coeff_matrix, type_con, lg_k,
            con_matrix, ign_indices)

# calculation of F_min and unknown enthalpies (starting point)
F_min, dH_res_out, disp = cl_enthalpies(ser_num, ser_counts, c_res_out, devs, volumes, heats, dH_ind, dH_par, dH_ind_wtf, 
                               _calor_setup_type_coeff, _calor_setup_type)

# F_min assignment for further calculations
new_min = F_min

# constant refinment
if len(tar_num) > 0:
    F_min, lg_k, dH_res_out, c_res_out, disp = cl_hooke_jeeves(F_min, tar_num, lg_k, step_init, max_iter, eps, ser_num, st_coeff_matrix, type_con,
        con_matrix, ign_indices, ser_counts, ser_info, devs, volumes, heats, dH_ind, dH_par, dH_ind_wtf, 
                _calor_setup_type_coeff, _calor_setup_type)


F_min, dH_res_out, disp = cl_enthalpies(ser_num, ser_counts, c_res_out, devs, volumes, heats, dH_ind, dH_par, dH_ind_wtf, 
                               _calor_setup_type_coeff, _calor_setup_type)

# error estimation
if len(tar_num) > 0:
    errs_values = cl_constants_errs(lg_k, heats, tar_num, HJ_eps, max_iter, eps, st_coeff_matrix, type_con, con_matrix,
                                    ign_indices, ser_num, ser_counts, devs, volumes, dH_ind, dH_par, dH_ind_wtf, 
                                    _calor_setup_type_coeff, _calor_setup_type)


eq con
[[9.09090909e-17 1.00000000e-03 9.09090909e-18 8.26446281e-33]
 [4.80628320e-04 3.80937585e-03 1.83089392e-04 8.79979466e-07]
 [9.69774435e-04 3.63115724e-03 3.52140346e-04 3.41496705e-06]
 [1.46675059e-03 3.46449370e-03 5.08154817e-04 7.45336377e-06]
 [1.97089999e-03 3.30857422e-03 6.52086891e-04 1.28519805e-05]
 [2.48160007e-03 3.16263100e-03 7.84838531e-04 1.94765535e-05]
 [2.99826431e-03 3.02594153e-03 9.07257248e-04 2.72019703e-05]
 [3.52034305e-03 2.89782936e-03 1.02013535e-03 3.59122637e-05]
 [4.04732338e-03 2.77766384e-03 1.12421038e-03 4.55004297e-05]
 [4.57872839e-03 2.66485901e-03 1.22016656e-03 5.58681127e-05]
 [5.11411588e-03 2.55887199e-03 1.30863678e-03 6.69252015e-05]
 [5.65307684e-03 2.45920088e-03 1.39020515e-03 7.85893657e-05]
 [6.19523366e-03 2.36538255e-03 1.46540976e-03 9.07855586e-05]
 [6.74023816e-03 2.27699017e-03 1.53474560e-03 1.03445509e-04]
 [7.28776969e-03 2.19363076e-03 1.59866757e-03 1.16507211e-04]
 [7.83753319e-03 2.11494274e-03 1.65759339e-03 


eq con
[[2.40253075e-17 1.00000000e-03 7.59746932e-17 1.82531537e-32]
 [5.67983087e-05 3.38501119e-03 6.07988707e-04 3.45327303e-07]
 [1.34757533e-04 2.79433003e-03 1.19077786e-03 1.60466286e-06]
 [2.45134832e-04 2.23968052e-03 1.73616541e-03 4.25594616e-06]
 [4.04833690e-04 1.73866687e-03 2.22583529e-03 9.01093115e-06]
 [6.34963869e-04 1.31326186e-03 2.63694060e-03 1.67436201e-05]
 [9.51960199e-04 9.80535085e-04 2.95176602e-03 2.80996377e-05]
 [1.35532173e-03 7.39873378e-04 3.17102599e-03 4.29776042e-05]
 [1.82785344e-03 5.73260267e-04 3.31354759e-03 6.05667938e-05]
 [2.34809784e-03 4.58259889e-04 3.40273427e-03 7.98995300e-05]
 [2.89904703e-03 3.77101173e-04 3.45710957e-03 1.00223232e-04]
 [3.46942573e-03 3.18006660e-04 3.48894248e-03 1.21046268e-04]
 [4.05216955e-03 2.73598451e-04 3.50591387e-03 1.42065574e-04]
 [4.64285855e-03 2.39260552e-04 3.51282532e-03 1.63095511e-04]
 [5.23866891e-03 2.12043622e-04 3.51274130e-03 1.84020886e-04]
 [5.83774486e-03 1.90008897e-04 3.50767257e-03 


eq con
[[2.40253075e-17 1.00000000e-03 7.59746932e-17 5.77215400e-32]
 [5.66623035e-05 3.38561685e-03 6.06641383e-04 1.08699178e-06]
 [1.33951124e-04 2.79693748e-03 1.18475656e-03 5.01851796e-06]
 [2.42341958e-04 2.24582133e-03 1.72109093e-03 1.31896244e-05]
 [3.97037935e-04 1.74943817e-03 2.19649693e-03 2.75779897e-05]
 [6.16229026e-04 1.32822103e-03 2.58828743e-03 5.04376279e-05]
 [9.13426481e-04 9.97094066e-04 2.88011434e-03 8.31923376e-05]
 [1.28796081e-03 7.54733259e-04 3.07394531e-03 1.25198402e-04]
 [1.72555921e-03 5.84410724e-04 3.18895245e-03 1.74011484e-04]
 [2.20814090e-03 4.65257850e-04 3.24878141e-03 2.26854434e-04]
 [2.72092543e-03 3.80334588e-04 3.27252116e-03 2.81578248e-04]
 [3.25378818e-03 3.18105372e-04 3.27310758e-03 3.36782531e-04]
 [3.80019476e-03 2.71175198e-04 3.25878584e-03 3.91617125e-04]
 [4.35594724e-03 2.34833724e-04 3.23476753e-03 4.45579997e-04]
 [4.91829644e-03 2.06030413e-04 3.20439492e-03 4.98380150e-04]
 [5.48539049e-03 1.82739383e-04 3.16985724e-03 


eq con
[[2.40253075e-17 1.00000000e-03 7.59746932e-17 3.24592073e-32]
 [5.67492061e-05 3.38522983e-03 6.07502331e-04 6.13066716e-07]
 [1.34465074e-04 2.79527504e-03 1.18859539e-03 2.84212736e-06]
 [2.44115206e-04 2.24191788e-03 1.73067107e-03 7.51293040e-06]
 [4.01961267e-04 1.74261677e-03 2.21506306e-03 1.58332585e-05]
 [6.27983166e-04 1.31878375e-03 2.61891612e-03 2.92462098e-05]
 [9.37442777e-04 9.86678177e-04 2.92496241e-03 4.87601527e-05]
 [1.32971326e-03 7.45402421e-04 3.13435943e-03 7.41151166e-05]
 [1.78869090e-03 5.77417821e-04 3.26606994e-03 1.03886897e-04]
 [2.29420264e-03 4.60875449e-04 3.34360795e-03 1.36410288e-04]
 [2.83008942e-03 3.78313485e-04 3.38572734e-03 1.70393153e-04]
 [3.38551711e-03 3.18043810e-04 3.40495958e-03 2.04992029e-04]
 [3.95362956e-03 2.72682490e-04 3.40920585e-03 2.39689605e-04]
 [4.53010010e-03 2.37579474e-04 3.40342915e-03 2.74172892e-04]
 [5.11214320e-03 2.09748932e-04 3.39080464e-03 3.08251912e-04]
 [5.69791471e-03 1.87220877e-04 3.37341847e-03 

eq con
[[2.40253075e-17 1.00000000e-03 7.59746932e-17 3.74833078e-32]
 [5.67318809e-05 3.38530698e-03 6.07330705e-04 7.07542319e-07]
 [1.34362241e-04 2.79560749e-03 1.18782766e-03 3.27740922e-06]
 [2.43758530e-04 2.24270176e-03 1.72874663e-03 8.65348744e-06]
 [4.00963713e-04 1.74399366e-03 2.21131174e-03 1.82076980e-05]
 [6.25580443e-04 1.32069853e-03 2.61268384e-03 3.35637147e-05]
 [9.32490676e-04 9.88799744e-04 2.91576718e-03 5.58338199e-05]
 [1.32104300e-03 7.47307237e-04 3.12187955e-03 8.46901880e-05]
 [1.77550973e-03 5.78847571e-04 3.25002927e-03 1.18497811e-04]
 [2.27615327e-03 4.61773060e-04 3.32376335e-03 1.55357276e-04]
 [2.80710178e-03 3.78728424e-04 3.36190982e-03 1.93795737e-04]
 [3.35766970e-03 3.18056485e-04 3.37708682e-03 2.32852121e-04]
 [3.92106963e-03 2.72371121e-04 3.37726869e-03 2.71938168e-04]
 [4.49300412e-03 2.37010254e-04 3.36747169e-03 3.10699654e-04]
 [5.07069791e-03 2.08975142e-04 3.35090693e-03 3.48923407e-04]
 [5.65230802e-03 1.86284711e-04 3.32968411e-03 3


eq con
[[2.33747473e-17 1.00000000e-03 7.66252537e-17 3.54808365e-32]
 [5.49276900e-05 3.38345814e-03 6.09224194e-04 6.62893067e-07]
 [1.30299688e-04 2.79134504e-03 1.19229000e-03 3.07751570e-06]
 [2.36973733e-04 2.23541537e-03 1.73653461e-03 8.15189641e-06]
 [3.91238965e-04 1.73329003e-03 2.22299425e-03 1.72288163e-05]
 [6.13430861e-04 1.30692125e-03 2.62808883e-03 3.19360104e-05]
 [9.19428849e-04 9.73335792e-04 2.93363326e-03 5.34316945e-05]
 [1.30891723e-03 7.31922189e-04 3.14052387e-03 8.14309093e-05]
 [1.76555624e-03 5.64706759e-04 3.26835740e-03 1.14310493e-04]
 [2.26882811e-03 4.49270175e-04 3.34144397e-03 1.50179543e-04]
 [2.80240481e-03 3.67820556e-04 3.37902859e-03 1.87584839e-04]
 [3.35542426e-03 3.08547122e-04 3.39386013e-03 2.25588200e-04]
 [3.92105796e-03 2.64041856e-04 3.39391560e-03 2.63620573e-04]
 [4.49501769e-03 2.29665767e-04 3.38417389e-03 3.01341591e-04]
 [5.07455169e-03 2.02453016e-04 3.36780496e-03 3.38547502e-04]
 [5.65784169e-03 1.80453150e-04 3.34688090e-03 


eq con
[[2.43551950e-17 1.00000000e-03 7.56448056e-17 3.85197289e-32]
 [5.76534718e-05 3.38625195e-03 6.06362357e-04 7.30920593e-07]
 [1.36432534e-04 2.79778219e-03 1.18554855e-03 3.38181456e-06]
 [2.47204786e-04 2.24640915e-03 1.72477812e-03 8.91461533e-06]
 [4.05883208e-04 1.74942074e-03 2.20537707e-03 1.87152847e-05]
 [6.31702882e-04 1.32766159e-03 2.60488017e-03 3.44043302e-05]
 [9.39059836e-04 9.96605329e-04 2.90672517e-03 5.70702451e-05]
 [1.32714440e-03 7.55081994e-04 3.11243143e-03 8.63635470e-05]
 [1.78052739e-03 5.86010596e-04 3.24072088e-03 1.20643182e-04]
 [2.27985337e-03 4.68121455e-04 3.31476667e-03 1.58005564e-04]
 [2.80947824e-03 3.84277349e-04 3.35318842e-03 1.96968206e-04]
 [3.35880716e-03 3.22900461e-04 3.36853633e-03 2.36558635e-04]
 [3.92107555e-03 2.76617786e-04 3.36878125e-03 2.76178916e-04]
 [4.49198271e-03 2.40756956e-04 3.35895681e-03 3.15467770e-04]
 [5.06874235e-03 2.12303441e-04 3.34229478e-03 3.54207267e-04]
 [5.64949948e-03 1.89261079e-04 3.32092283e-03 


eq con
[[2.40253075e-17 1.00000000e-03 7.59746932e-17 3.78219712e-32]
 [5.67307138e-05 3.38531217e-03 6.07319143e-04 7.13906717e-07]
 [1.34355320e-04 2.79562986e-03 1.18777598e-03 3.30670656e-06]
 [2.43734560e-04 2.24275447e-03 1.72861725e-03 8.73016007e-06]
 [4.00896806e-04 1.74408610e-03 2.21105994e-03 1.83670481e-05]
 [6.25419682e-04 1.32082691e-03 2.61226632e-03 3.38528507e-05]
 [9.32160142e-04 9.88941829e-04 2.91515248e-03 5.63064381e-05]
 [1.32046545e-03 7.47434723e-04 3.12104702e-03 8.53952281e-05]
 [1.77463306e-03 5.78943219e-04 3.24896130e-03 1.19470135e-04]
 [2.27495437e-03 4.61833077e-04 3.32244442e-03 1.56616193e-04]
 [2.80557668e-03 3.78756149e-04 3.36032926e-03 1.95348566e-04]
 [3.35582429e-03 3.18057331e-04 3.37523972e-03 2.34698377e-04]
 [3.91891436e-03 2.72350353e-04 3.37515495e-03 2.74072675e-04]
 [4.49055132e-03 2.36972327e-04 3.36509475e-03 3.13114523e-04]
 [5.06796057e-03 2.08923639e-04 3.34827260e-03 3.51609246e-04]
 [5.64929913e-03 1.86222470e-04 3.32679971e-03 

eq con
[[2.40253075e-17 1.00000000e-03 7.59746932e-17 3.73151150e-32]
 [5.67324605e-05 3.38530439e-03 6.07336447e-04 7.04381335e-07]
 [1.34365678e-04 2.79559637e-03 1.18785332e-03 3.26285700e-06]
 [2.43770438e-04 2.24267558e-03 1.72881090e-03 8.61539915e-06]
 [4.00996957e-04 1.74394773e-03 2.21143684e-03 1.81285259e-05]
 [6.25660339e-04 1.32063474e-03 2.61289131e-03 3.34200307e-05]
 [9.32654984e-04 9.88729137e-04 2.91607270e-03 5.55989049e-05]
 [1.32133015e-03 7.47243880e-04 3.12229341e-03 8.43396772e-05]
 [1.77594567e-03 5.78800035e-04 3.25056028e-03 1.18014338e-04]
 [2.27674951e-03 4.61743231e-04 3.32441925e-03 1.54731208e-04]
 [2.80786033e-03 3.78714643e-04 3.36269593e-03 1.93023406e-04]
 [3.35858766e-03 3.18056064e-04 3.37800562e-03 2.31933740e-04]
 [3.92214184e-03 2.72381446e-04 3.37832024e-03 2.70876286e-04]
 [4.49422446e-03 2.37029111e-04 3.36865432e-03 3.09498167e-04]
 [5.07205997e-03 2.09000750e-04 3.35221777e-03 3.47586963e-04]
 [5.65380534e-03 1.86315662e-04 3.33111952e-03 3


eq con
[[2.39433147e-17 1.00000000e-03 7.60566860e-17 3.73117062e-32]
 [5.65032384e-05 3.38507417e-03 6.07567667e-04 7.03382293e-07]
 [1.33847042e-04 2.79507390e-03 1.18837963e-03 3.25902291e-06]
 [2.42896670e-04 2.24179468e-03 1.72969894e-03 8.60826279e-06]
 [3.99723250e-04 1.74266765e-03 2.21272328e-03 1.81221596e-05]
 [6.24014994e-04 1.31899738e-03 2.61452069e-03 3.34280117e-05]
 [9.30770424e-04 9.86891298e-04 2.91786382e-03 5.56456259e-05]
 [1.31937833e-03 7.45403771e-04 3.12402180e-03 8.44513972e-05]
 [1.77404188e-03 5.77090216e-04 3.25207613e-03 1.18208310e-04]
 [2.27493434e-03 4.60210981e-04 3.32566859e-03 1.55014125e-04]
 [2.80613166e-03 3.77358009e-04 3.36368053e-03 1.93395437e-04]
 [3.35692830e-03 3.16855060e-04 3.37874828e-03 2.32392090e-04]
 [3.92053252e-03 2.71312916e-04 3.37884800e-03 2.71417067e-04]
 [4.49264830e-03 2.36072002e-04 3.36899239e-03 3.10117225e-04]
 [5.07050336e-03 2.08137372e-04 3.35238792e-03 3.48280195e-04]
 [5.65225776e-03 1.85531570e-04 3.33114013e-03 


eq con
[[2.39433147e-17 1.00000000e-03 7.60566860e-17 3.76488191e-32]
 [5.65020828e-05 3.38507935e-03 6.07556169e-04 7.09709435e-07]
 [1.33840185e-04 2.79509618e-03 1.18832822e-03 3.28815760e-06]
 [2.42872896e-04 2.24184718e-03 1.72957015e-03 8.68454203e-06]
 [3.99656804e-04 1.74275983e-03 2.21247248e-03 1.82807822e-05]
 [6.23855086e-04 1.31912549e-03 2.61410457e-03 3.37160248e-05]
 [9.30441164e-04 9.87033145e-04 2.91725087e-03 5.61167332e-05]
 [1.31880242e-03 7.45531045e-04 3.12319134e-03 8.51545806e-05]
 [1.77316721e-03 5.77185692e-04 3.25101051e-03 1.19178455e-04]
 [2.27373784e-03 4.60270902e-04 3.32435225e-03 1.56270540e-04]
 [2.80460940e-03 3.77385735e-04 3.36210281e-03 1.94945432e-04]
 [3.35508617e-03 3.16856006e-04 3.37690425e-03 2.34235175e-04]
 [3.91838095e-03 2.71292339e-04 3.37673758e-03 2.73548069e-04]
 [4.49019960e-03 2.36034344e-04 3.36661901e-03 3.12528268e-04]
 [5.06777048e-03 2.08086205e-04 3.34975737e-03 3.50961904e-04]
 [5.64925368e-03 1.85469718e-04 3.32825975e-03 


eq con
[[2.39433147e-17 1.00000000e-03 7.60566860e-17 3.79889779e-32]
 [5.65009167e-05 3.38508456e-03 6.07544567e-04 7.16093239e-07]
 [1.33833267e-04 2.79511865e-03 1.18827635e-03 3.31754995e-06]
 [2.42848917e-04 2.24190015e-03 1.72944025e-03 8.76148397e-06]
 [3.99589800e-04 1.74285279e-03 2.21221955e-03 1.84407490e-05]
 [6.23693885e-04 1.31925466e-03 2.61368502e-03 3.40064011e-05]
 [9.30109340e-04 9.87176157e-04 2.91663302e-03 5.65915685e-05]
 [1.31822217e-03 7.45659355e-04 3.12235448e-03 8.58631378e-05]
 [1.77228612e-03 5.77281940e-04 3.24993692e-03 1.20155791e-04]
 [2.27253276e-03 4.60331303e-04 3.32302636e-03 1.57536023e-04]
 [2.80307643e-03 3.77413681e-04 3.36051395e-03 1.96506346e-04]
 [3.35323134e-03 3.16856959e-04 3.37504752e-03 2.36090953e-04]
 [3.91621485e-03 2.71271603e-04 3.37461295e-03 2.75693430e-04]
 [4.48773471e-03 2.35996401e-04 3.36423001e-03 3.14955209e-04]
 [5.06501992e-03 2.08034657e-04 3.34710991e-03 3.53660917e-04]
 [5.64623056e-03 1.85407414e-04 3.32536125e-03 


eq con
[[2.39637949e-17 1.00000000e-03 7.60362058e-17 3.81825645e-32]
 [5.65574801e-05 3.38514500e-03 6.07480261e-04 7.19964834e-07]
 [1.33958826e-04 2.79526184e-03 1.18811553e-03 3.33517840e-06]
 [2.43053485e-04 2.24215012e-03 1.72914488e-03 8.80688445e-06]
 [3.99869896e-04 1.74322510e-03 2.21175503e-03 1.85329603e-05]
 [6.24013558e-04 1.31973670e-03 2.61304063e-03 3.41687625e-05]
 [9.30392418e-04 9.87716081e-04 2.91583625e-03 5.68484144e-05]
 [1.31838185e-03 7.46191509e-04 3.12144985e-03 8.62356101e-05]
 [1.77226406e-03 5.77763386e-04 3.24895197e-03 1.20659295e-04]
 [2.27230578e-03 4.60748088e-04 3.32196581e-03 1.58179790e-04]
 [2.80264287e-03 3.77768210e-04 3.35937134e-03 1.97294435e-04]
 [3.35259891e-03 3.17157321e-04 3.37381437e-03 2.37023740e-04]
 [3.91539436e-03 2.71526586e-04 3.37328250e-03 2.76768900e-04]
 [4.48673745e-03 2.36213803e-04 3.36279794e-03 3.16169878e-04]
 [5.06385668e-03 2.08220941e-04 3.34557410e-03 3.55010438e-04]
 [5.64491141e-03 1.85567804e-04 3.32372131e-03 


eq con
[[2.39637949e-17 1.00000000e-03 7.60362058e-17 3.82685191e-32]
 [5.65571851e-05 3.38514632e-03 6.07477329e-04 7.21578335e-07]
 [1.33957077e-04 2.79526752e-03 1.18810243e-03 3.34260585e-06]
 [2.43047423e-04 2.24216349e-03 1.72911207e-03 8.82632240e-06]
 [3.99852966e-04 1.74324857e-03 2.21169116e-03 1.85733580e-05]
 [6.23972857e-04 1.31976929e-03 2.61293473e-03 3.42420601e-05]
 [9.30308696e-04 9.87752160e-04 2.91568037e-03 5.69682159e-05]
 [1.31823553e-03 7.46223876e-04 3.12123879e-03 8.64143032e-05]
 [1.77204195e-03 5.77787665e-04 3.24868130e-03 1.20905688e-04]
 [2.27200207e-03 4.60763323e-04 3.32163163e-03 1.58498740e-04]
 [2.80225659e-03 3.77775255e-04 3.35897097e-03 1.97687757e-04]
 [3.35213162e-03 3.17157555e-04 3.37334661e-03 2.37491272e-04]
 [3.91484873e-03 2.71521347e-04 3.37274735e-03 2.77309291e-04]
 [4.48611665e-03 2.36204224e-04 3.36219631e-03 3.16781094e-04]
 [5.06316405e-03 2.08207931e-04 3.34490749e-03 3.55690065e-04]
 [5.64415026e-03 1.85552083e-04 3.32299160e-03 


eq con
[[2.39433147e-17 1.00000000e-03 7.60566860e-17 3.83322100e-32]
 [5.64997403e-05 3.38508983e-03 6.07532862e-04 7.22534207e-07]
 [1.33826288e-04 2.79514133e-03 1.18822402e-03 3.34720220e-06]
 [2.42824731e-04 2.24195357e-03 1.72930921e-03 8.83909413e-06]
 [3.99522234e-04 1.74294655e-03 2.21196447e-03 1.86020706e-05]
 [6.23531382e-04 1.31938491e-03 2.61326201e-03 3.42991580e-05]
 [9.29774937e-04 9.87320343e-04 2.91601025e-03 5.70701571e-05]
 [1.31763756e-03 7.45788706e-04 3.12151116e-03 8.65771020e-05]
 [1.77139858e-03 5.77378964e-04 3.24885533e-03 1.21140358e-04]
 [2.27131905e-03 4.60392188e-04 3.32169088e-03 1.58810621e-04]
 [2.80153271e-03 3.77441848e-04 3.35891390e-03 1.98078234e-04]
 [3.35136377e-03 3.16857920e-04 3.37317803e-03 2.37959485e-04]
 [3.91403417e-03 2.71250708e-04 3.37247407e-03 2.77853211e-04]
 [4.48525358e-03 2.35958171e-04 3.36182535e-03 3.17398110e-04]
 [5.06225161e-03 2.07982726e-04 3.34444546e-03 3.56377299e-04]
 [5.64318835e-03 1.85344657e-04 3.32244455e-03 


eq con
[[2.39433147e-17 1.00000000e-03 7.60566860e-17 3.83537647e-32]
 [5.64996664e-05 3.38509016e-03 6.07532127e-04 7.22938677e-07]
 [1.33825850e-04 2.79514275e-03 1.18822074e-03 3.34906415e-06]
 [2.42823212e-04 2.24195692e-03 1.72930099e-03 8.84396708e-06]
 [3.99517992e-04 1.74295244e-03 2.21194846e-03 1.86121984e-05]
 [6.23521182e-04 1.31939309e-03 2.61323546e-03 3.43175347e-05]
 [9.29753951e-04 9.87329393e-04 2.91597116e-03 5.71001941e-05]
 [1.31760087e-03 7.45796825e-04 3.12145824e-03 8.66219051e-05]
 [1.77134289e-03 5.77385054e-04 3.24878747e-03 1.21202134e-04]
 [2.27124291e-03 4.60396009e-04 3.32160709e-03 1.58890588e-04]
 [2.80143586e-03 3.77443615e-04 3.35881352e-03 1.98176843e-04]
 [3.35124662e-03 3.16857981e-04 3.37306076e-03 2.38076693e-04]
 [3.91389740e-03 2.71249397e-04 3.37233991e-03 2.77988677e-04]
 [4.48509797e-03 2.35955772e-04 3.36167454e-03 3.17551323e-04]
 [5.06207800e-03 2.07979467e-04 3.34427836e-03 3.56547651e-04]
 [5.64299758e-03 1.85340719e-04 3.32226165e-03 


eq con
[[2.39433147e-17 1.00000000e-03 7.60566860e-17 3.84401047e-32]
 [5.64993705e-05 3.38509148e-03 6.07529182e-04 7.24558813e-07]
 [1.33824095e-04 2.79514845e-03 1.18820758e-03 3.35652218e-06]
 [2.42817130e-04 2.24197036e-03 1.72926803e-03 8.86348523e-06]
 [3.99501003e-04 1.74297601e-03 2.21188432e-03 1.86527631e-05]
 [6.23480330e-04 1.31942584e-03 2.61312911e-03 3.43911355e-05]
 [9.29669905e-04 9.87365643e-04 2.91581461e-03 5.72204898e-05]
 [1.31745397e-03 7.45829344e-04 3.12124630e-03 8.68013301e-05]
 [1.77111989e-03 5.77409444e-04 3.24851569e-03 1.21449525e-04]
 [2.27093799e-03 4.60411314e-04 3.32127157e-03 1.59210810e-04]
 [2.80104808e-03 3.77450695e-04 3.35841158e-03 1.98571708e-04]
 [3.35077753e-03 3.16858222e-04 3.37259119e-03 2.38546026e-04]
 [3.91334971e-03 2.71244146e-04 3.37180273e-03 2.78531109e-04]
 [4.48447489e-03 2.35946165e-04 3.36107067e-03 3.18164800e-04]
 [5.06138286e-03 2.07966419e-04 3.34360932e-03 3.57229740e-04]
 [5.64223373e-03 1.85324952e-04 3.32152934e-03 


eq con
[[2.39433147e-17 1.00000000e-03 7.60566860e-17 3.84725323e-32]
 [5.64992593e-05 3.38509198e-03 6.07528076e-04 7.25167295e-07]
 [1.33823435e-04 2.79515060e-03 1.18820263e-03 3.35932318e-06]
 [2.42814846e-04 2.24197541e-03 1.72925566e-03 8.87081541e-06]
 [3.99494623e-04 1.74298487e-03 2.21186023e-03 1.86679969e-05]
 [6.23464990e-04 1.31943814e-03 2.61308917e-03 3.44187745e-05]
 [9.29638345e-04 9.87379255e-04 2.91575583e-03 5.72656617e-05]
 [1.31739880e-03 7.45841555e-04 3.12116671e-03 8.68687022e-05]
 [1.77103616e-03 5.77418603e-04 3.24841364e-03 1.21542413e-04]
 [2.27082350e-03 4.60417061e-04 3.32114559e-03 1.59331042e-04]
 [2.80090249e-03 3.77453354e-04 3.35826067e-03 1.98719961e-04]
 [3.35060141e-03 3.16858313e-04 3.37241489e-03 2.38722232e-04]
 [3.91314410e-03 2.71242174e-04 3.37160106e-03 2.78734755e-04]
 [4.48424097e-03 2.35942557e-04 3.36084396e-03 3.18395113e-04]
 [5.06112189e-03 2.07961519e-04 3.34335816e-03 3.57485805e-04]
 [5.64194698e-03 1.85319031e-04 3.32125443e-03 


eq con
[[2.39433147e-17 1.00000000e-03 7.60566860e-17 3.85049873e-32]
 [5.64991481e-05 3.38509248e-03 6.07526970e-04 7.25776286e-07]
 [1.33822776e-04 2.79515274e-03 1.18819769e-03 3.36212649e-06]
 [2.42812559e-04 2.24198046e-03 1.72924327e-03 8.87815154e-06]
 [3.99488238e-04 1.74299373e-03 2.21183612e-03 1.86832427e-05]
 [6.23449638e-04 1.31945045e-03 2.61304920e-03 3.44464346e-05]
 [9.29606763e-04 9.87392878e-04 2.91569700e-03 5.73108668e-05]
 [1.31734361e-03 7.45853775e-04 3.12108707e-03 8.69361223e-05]
 [1.77095237e-03 5.77427769e-04 3.24831152e-03 1.21635366e-04]
 [2.27070894e-03 4.60422813e-04 3.32101952e-03 1.59451354e-04]
 [2.80075680e-03 3.77456014e-04 3.35810965e-03 1.98868311e-04]
 [3.35042519e-03 3.16858404e-04 3.37223848e-03 2.38898552e-04]
 [3.91293835e-03 2.71240201e-04 3.37139926e-03 2.78938528e-04]
 [4.48400690e-03 2.35938948e-04 3.36061712e-03 3.18625566e-04]
 [5.06086077e-03 2.07956616e-04 3.34310684e-03 3.57742023e-04]
 [5.64166007e-03 1.85313107e-04 3.32097936e-03 


eq con
[[2.39433147e-17 1.00000000e-03 7.60566860e-17 3.85483031e-32]
 [5.64989996e-05 3.38509314e-03 6.07525493e-04 7.26589066e-07]
 [1.33821895e-04 2.79515560e-03 1.18819109e-03 3.36586783e-06]
 [2.42809508e-04 2.24198720e-03 1.72922674e-03 8.88794229e-06]
 [3.99479717e-04 1.74300555e-03 2.21180395e-03 1.87035893e-05]
 [6.23429151e-04 1.31946687e-03 2.61299586e-03 3.44833477e-05]
 [9.29564618e-04 9.87411058e-04 2.91561849e-03 5.73711922e-05]
 [1.31726995e-03 7.45870084e-04 3.12098080e-03 8.70260904e-05]
 [1.77084057e-03 5.77440001e-04 3.24817525e-03 1.21759403e-04]
 [2.27055608e-03 4.60430488e-04 3.32085131e-03 1.59611896e-04]
 [2.80056240e-03 3.77459565e-04 3.35790815e-03 1.99066261e-04]
 [3.35019004e-03 3.16858525e-04 3.37200309e-03 2.39133820e-04]
 [3.91266382e-03 2.71237567e-04 3.37113000e-03 2.79210424e-04]
 [4.48369460e-03 2.35934130e-04 3.36031445e-03 3.18933057e-04]
 [5.06051237e-03 2.07950074e-04 3.34277152e-03 3.58083886e-04]
 [5.64127724e-03 1.85305202e-04 3.32061235e-03 

 0.00332904 0.00306601]
[0.09132 0.08796 0.08285 0.07515 0.06428 0.05097 0.03771 0.02695 0.01934
 0.01428 0.01094 0.00868 0.00711 0.00599 0.00516 0.00452 0.00403 0.00364
 0.00332 0.00306]
input [3.5020752] 4.062831974994366e-09

eq con
[[2.39356377e-17 1.00000000e-03 7.60643630e-17 3.85560855e-32]
 [5.64775268e-05 3.38507172e-03 6.07546854e-04 7.26644760e-07]
 [1.33773207e-04 2.79510724e-03 1.18823911e-03 3.36619818e-06]
 [2.42727181e-04 2.24190601e-03 1.72930678e-03 8.88908696e-06]
 [3.99358923e-04 1.74288795e-03 2.21191835e-03 1.87067862e-05]
 [6.23271282e-04 1.31931669e-03 2.61313836e-03 3.44910345e-05]
 [9.29380186e-04 9.87242440e-04 2.91577130e-03 5.73870058e-05]
 [1.31707313e-03 7.45700907e-04 3.12112233e-03 8.70537293e-05]
 [1.77064088e-03 5.77282265e-04 3.24829103e-03 1.21801355e-04]
 [2.27035676e-03 4.60288533e-04 3.32093590e-03 1.59669255e-04]
 [2.80036318e-03 3.77333290e-04 3.35796149e-03 1.99139205e-04]
 [3.34998947e-03 3.16746187e-04 3.37202720e-03 2.39222051e-04]
 [3.9124


eq con
[[2.39356377e-17 1.00000000e-03 7.60643630e-17 3.85669242e-32]
 [5.64774897e-05 3.38507189e-03 6.07546484e-04 7.26848112e-07]
 [1.33772986e-04 2.79510796e-03 1.18823746e-03 3.36713425e-06]
 [2.42726418e-04 2.24190770e-03 1.72930264e-03 8.89153660e-06]
 [3.99356792e-04 1.74289091e-03 2.21191030e-03 1.87118771e-05]
 [6.23266157e-04 1.31932080e-03 2.61312501e-03 3.45002706e-05]
 [9.29369642e-04 9.87246990e-04 2.91575165e-03 5.74021002e-05]
 [1.31705470e-03 7.45704988e-04 3.12109574e-03 8.70762411e-05]
 [1.77061291e-03 5.77285326e-04 3.24825694e-03 1.21832392e-04]
 [2.27031851e-03 4.60290454e-04 3.32089381e-03 1.59709426e-04]
 [2.80031454e-03 3.77334178e-04 3.35791107e-03 1.99188735e-04]
 [3.34993063e-03 3.16746218e-04 3.37196830e-03 2.39280918e-04]
 [3.91239168e-03 2.71136467e-04 3.37106006e-03 2.79381463e-04]
 [4.48340886e-03 2.35842514e-04 3.36021195e-03 3.19127175e-04]
 [5.06021252e-03 2.07866484e-04 3.34263885e-03 3.58300145e-04]
 [5.64096305e-03 1.85228444e-04 3.32045167e-03 


eq con
[[2.39356377e-17 1.00000000e-03 7.60643630e-17 3.85886109e-32]
 [5.64774154e-05 3.38507222e-03 6.07545745e-04 7.27254986e-07]
 [1.33772546e-04 2.79510939e-03 1.18823416e-03 3.36900716e-06]
 [2.42724891e-04 2.24191107e-03 1.72929437e-03 8.89643789e-06]
 [3.99352527e-04 1.74289683e-03 2.21189419e-03 1.87220627e-05]
 [6.23255902e-04 1.31932903e-03 2.61309831e-03 3.45187498e-05]
 [9.29348545e-04 9.87256093e-04 2.91571235e-03 5.74323002e-05]
 [1.31701783e-03 7.45713154e-04 3.12104254e-03 8.71212807e-05]
 [1.77055694e-03 5.77291451e-04 3.24818872e-03 1.21894486e-04]
 [2.27024199e-03 4.60294297e-04 3.32080960e-03 1.59789794e-04]
 [2.80021722e-03 3.77335956e-04 3.35781020e-03 1.99287829e-04]
 [3.34981292e-03 3.16746279e-04 3.37185046e-03 2.39398690e-04]
 [3.91225426e-03 2.71135150e-04 3.37092527e-03 2.79517567e-04]
 [4.48325253e-03 2.35840103e-04 3.36006044e-03 3.19281093e-04]
 [5.06003812e-03 2.07863210e-04 3.34247101e-03 3.58471265e-04]
 [5.64077143e-03 1.85224488e-04 3.32026797e-03 


eq con
[[2.39356377e-17 1.00000000e-03 7.60643630e-17 3.86103098e-32]
 [5.64773411e-05 3.38507256e-03 6.07545005e-04 7.27662087e-07]
 [1.33772105e-04 2.79511082e-03 1.18823085e-03 3.37088111e-06]
 [2.42723363e-04 2.24191445e-03 1.72928609e-03 8.90134182e-06]
 [3.99348260e-04 1.74290276e-03 2.21187808e-03 1.87322537e-05]
 [6.23245643e-04 1.31933726e-03 2.61307159e-03 3.45372385e-05]
 [9.29327438e-04 9.87265201e-04 2.91567303e-03 5.74625150e-05]
 [1.31698093e-03 7.45721324e-04 3.12098931e-03 8.71663417e-05]
 [1.77050094e-03 5.77297578e-04 3.24812047e-03 1.21956609e-04]
 [2.27016543e-03 4.60298142e-04 3.32072535e-03 1.59870198e-04]
 [2.80011986e-03 3.77337735e-04 3.35770928e-03 1.99386966e-04]
 [3.34969516e-03 3.16746341e-04 3.37173258e-03 2.39516512e-04]
 [3.91211678e-03 2.71133832e-04 3.37079043e-03 2.79653728e-04]
 [4.48309614e-03 2.35837692e-04 3.35990887e-03 3.19435075e-04]
 [5.05986366e-03 2.07859934e-04 3.34230310e-03 3.58642453e-04]
 [5.64057974e-03 1.85220530e-04 3.32008419e-03 


eq con
[[2.39356377e-17 1.00000000e-03 7.60643630e-17 3.86320208e-32]
 [5.64772667e-05 3.38507289e-03 6.07544265e-04 7.28069415e-07]
 [1.33771664e-04 2.79511226e-03 1.18822754e-03 3.37275608e-06]
 [2.42721834e-04 2.24191783e-03 1.72927780e-03 8.90624840e-06]
 [3.99343991e-04 1.74290869e-03 2.21186196e-03 1.87424501e-05]
 [6.23235378e-04 1.31934549e-03 2.61304486e-03 3.45557366e-05]
 [9.29306321e-04 9.87274313e-04 2.91563369e-03 5.74927446e-05]
 [1.31694403e-03 7.45729498e-04 3.12093605e-03 8.72114240e-05]
 [1.77044492e-03 5.77303709e-04 3.24805218e-03 1.22018761e-04]
 [2.27008883e-03 4.60301989e-04 3.32064106e-03 1.59950638e-04]
 [2.80002246e-03 3.77339515e-04 3.35760832e-03 1.99486146e-04]
 [3.34957735e-03 3.16746402e-04 3.37161465e-03 2.39634385e-04]
 [3.91197924e-03 2.71132513e-04 3.37065553e-03 2.79789946e-04]
 [4.48293968e-03 2.35835279e-04 3.35975724e-03 3.19589120e-04]
 [5.05968913e-03 2.07856657e-04 3.34213512e-03 3.58813710e-04]
 [5.64038797e-03 1.85216571e-04 3.31990034e-03 


eq con
[[2.39356377e-17 1.00000000e-03 7.60643630e-17 3.86428809e-32]
 [5.64772295e-05 3.38507306e-03 6.07543894e-04 7.28273164e-07]
 [1.33771443e-04 2.79511297e-03 1.18822588e-03 3.37369396e-06]
 [2.42721070e-04 2.24191952e-03 1.72927366e-03 8.90870268e-06]
 [3.99341856e-04 1.74291165e-03 2.21185389e-03 1.87475503e-05]
 [6.23230243e-04 1.31934961e-03 2.61303149e-03 3.45649891e-05]
 [9.29295758e-04 9.87278871e-04 2.91561401e-03 5.75078650e-05]
 [1.31692557e-03 7.45733587e-04 3.12090941e-03 8.72339732e-05]
 [1.77041690e-03 5.77306776e-04 3.24801803e-03 1.22049847e-04]
 [2.27005052e-03 4.60303913e-04 3.32059891e-03 1.59990872e-04]
 [2.79997375e-03 3.77340405e-04 3.35755782e-03 1.99535752e-04]
 [3.34951843e-03 3.16746433e-04 3.37155566e-03 2.39693340e-04]
 [3.91191045e-03 2.71131853e-04 3.37058806e-03 2.79858076e-04]
 [4.48286143e-03 2.35834072e-04 3.35968140e-03 3.19666165e-04]
 [5.05960183e-03 2.07855018e-04 3.34205110e-03 3.58899364e-04]
 [5.64029206e-03 1.85214590e-04 3.31980839e-03 


eq con
[[2.39356377e-17 1.00000000e-03 7.60643630e-17 3.86591768e-32]
 [5.64771737e-05 3.38507331e-03 6.07543339e-04 7.28578894e-07]
 [1.33771112e-04 2.79511405e-03 1.18822340e-03 3.37510125e-06]
 [2.42719923e-04 2.24192205e-03 1.72926744e-03 8.91238535e-06]
 [3.99338651e-04 1.74291610e-03 2.21184179e-03 1.87552032e-05]
 [6.23222539e-04 1.31935579e-03 2.61301142e-03 3.45788724e-05]
 [9.29279910e-04 9.87285711e-04 2.91558448e-03 5.75305526e-05]
 [1.31689787e-03 7.45739722e-04 3.12086944e-03 8.72678070e-05]
 [1.77037486e-03 5.77311377e-04 3.24796679e-03 1.22096490e-04]
 [2.26999304e-03 4.60306800e-04 3.32053565e-03 1.60051239e-04]
 [2.79990065e-03 3.77341741e-04 3.35748206e-03 1.99610181e-04]
 [3.34943002e-03 3.16746479e-04 3.37146716e-03 2.39781796e-04]
 [3.91180724e-03 2.71130864e-04 3.37048683e-03 2.79960298e-04]
 [4.48274402e-03 2.35832261e-04 3.35956761e-03 3.19781763e-04]
 [5.05947086e-03 2.07852559e-04 3.34192505e-03 3.59027877e-04]
 [5.64014816e-03 1.85211619e-04 3.31967043e-03 


eq con
[[2.39356377e-17 1.00000000e-03 7.60643630e-17 3.86700446e-32]
 [5.64771365e-05 3.38507347e-03 6.07542968e-04 7.28782784e-07]
 [1.33770891e-04 2.79511477e-03 1.18822174e-03 3.37603977e-06]
 [2.42719157e-04 2.24192374e-03 1.72926329e-03 8.91484130e-06]
 [3.99336515e-04 1.74291907e-03 2.21183372e-03 1.87603067e-05]
 [6.23217402e-04 1.31935991e-03 2.61299804e-03 3.45881309e-05]
 [9.29269341e-04 9.87290271e-04 2.91556479e-03 5.75456823e-05]
 [1.31687940e-03 7.45743813e-04 3.12084279e-03 8.72903695e-05]
 [1.77034682e-03 5.77314445e-04 3.24793261e-03 1.22127595e-04]
 [2.26995471e-03 4.60308725e-04 3.32049347e-03 1.60091495e-04]
 [2.79985191e-03 3.77342631e-04 3.35743153e-03 1.99659815e-04]
 [3.34937106e-03 3.16746509e-04 3.37140814e-03 2.39840783e-04]
 [3.91173842e-03 2.71130204e-04 3.37041932e-03 2.80028464e-04]
 [4.48266573e-03 2.35831054e-04 3.35949174e-03 3.19858848e-04]
 [5.05938352e-03 2.07850919e-04 3.34184099e-03 3.59113574e-04]
 [5.64005220e-03 1.85209637e-04 3.31957844e-03 

In [7]:
print(np.array(c_res_out))
#print(c_res_out[int(np.sum(ser_counts[:0])) + 1])

[[2.39381965e-17 1.00000000e-03 7.60618042e-17 3.86837491e-32]
 [5.64842374e-05 3.38508086e-03 6.07535293e-04 7.29070102e-07]
 [1.33786787e-04 2.79513196e-03 1.18820325e-03 3.37733756e-06]
 [2.42745449e-04 2.24195334e-03 1.72923040e-03 8.91814369e-06]
 [3.99373570e-04 1.74296271e-03 2.21178349e-03 1.87668956e-05]
 [6.23262314e-04 1.31941614e-03 2.61293049e-03 3.45994529e-05]
 [9.29314965e-04 9.87353310e-04 2.91548434e-03 5.75630970e-05]
 [1.31691730e-03 7.45806333e-04 3.12075565e-03 8.73149837e-05]
 [1.77037135e-03 5.77371619e-04 3.24784279e-03 1.22160241e-04]
 [2.26996369e-03 4.60358925e-04 3.32040204e-03 1.60132723e-04]
 [2.79984524e-03 3.77386054e-04 3.35733802e-03 1.99709904e-04]
 [3.34934953e-03 3.16783996e-04 3.37131164e-03 2.39899797e-04]
 [3.91170305e-03 2.71162690e-04 3.37031899e-03 2.80096314e-04]
 [4.48261755e-03 2.35859375e-04 3.35938692e-03 3.19935345e-04]
 [5.05932348e-03 2.07875772e-04 3.34173124e-03 3.59198468e-04]
 [5.63998115e-03 1.85231587e-04 3.31946349e-03 3.977553

In [8]:
#print('\nStoich coeff data')
#print(st_coeff_data)

#print('\nlg K')
#print(lg_k_data)

#print('\nconcentrations')
#print(con_data)

#print('\ntype con')
#print(type_con)

#print('\nexperimental data')
#print(heats_data)

print('\n_calor_setup_type_coeff')
print(_calor_setup_type_coeff)

print('\ntargets')
print(targets)

#print('\ndelta_H')
#print(delta_H)


_calor_setup_type_coeff
[[1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1]]

targets
            0   1    2
0  constants   HL  H2L


In [9]:
print('\nSeries')
print(ser_num)
print(ser_counts)
print(ser_info)

print('\nSt coeff matr')
print(st_coeff_matrix)

print('\nprod names')
print(prod_names)
print(prod_names_con)

print('\nconst')
print(lg_k)

print('\nconcentrations')
print(con_matrix)

print(ign_indices)

print('\ntype con')
print(type_con)

print('\nvolumes')
print(volumes)

print('\nheats')
print(heats)

print('\ndeviations')
print(devs)

print('\nwhat to find and what is known')
print(tar_num)
print(dH_ind)
print(dH_ind_wtf)

print('\nenthalpies')
print(dH_par)


Series
1
[21]
['' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '']

St coeff matr
[[1 0]
 [0 1]
 [1 1]
 [2 1]]

prod names
['H', 'L', 'HL', 'H2L']
['H', 'L']

const
[[0.        ]
 [0.        ]
 [3.50213623]
 [4.82928467]]

concentrations
[[1.00000000e-16 1.00000000e-03]
 [6.65477670e-04 3.99334522e-03]
 [1.32874472e-03 3.98671255e-03]
 [1.98981213e-03 3.98010188e-03]
 [2.64869085e-03 3.97351309e-03]
 [3.30539171e-03 3.96694608e-03]
 [3.95992550e-03 3.96040075e-03]
 [4.61230292e-03 3.95387697e-03]
 [5.26253463e-03 3.94737465e-03]
 [5.91063117e-03 3.94089369e-03]
 [6.55660306e-03 3.93443397e-03]
 [7.20046073e-03 3.92799539e-03]
 [7.84221453e-03 3.92157785e-03]
 [8.48187477e-03 3.91518125e-03]
 [9.11945166e-03 3.90880548e-03]
 [9.75495538e-03 3.90245045e-03]
 [1.03883960e-02 3.89611604e-03]
 [1.10197836e-02 3.88980216e-03]
 [1.16491281e-02 3.88350872e-03]
 [1.22764394e-02 3.87723561e-03]
 [1.29017274e-02 3.87098273e-03]]
[]

type con
0    tot
1    tot
Name: 0, dtype: object



In [10]:
print('\nEq conc')
print(np.array(c_res_out))
print(np.shape(c_res_out))


Eq conc
[[2.39381965e-17 1.00000000e-03 7.60618042e-17 3.86837491e-32]
 [5.64842374e-05 3.38508086e-03 6.07535293e-04 7.29070102e-07]
 [1.33786787e-04 2.79513196e-03 1.18820325e-03 3.37733756e-06]
 [2.42745449e-04 2.24195334e-03 1.72923040e-03 8.91814369e-06]
 [3.99373570e-04 1.74296271e-03 2.21178349e-03 1.87668956e-05]
 [6.23262314e-04 1.31941614e-03 2.61293049e-03 3.45994529e-05]
 [9.29314965e-04 9.87353310e-04 2.91548434e-03 5.75630970e-05]
 [1.31691730e-03 7.45806333e-04 3.12075565e-03 8.73149837e-05]
 [1.77037135e-03 5.77371619e-04 3.24784279e-03 1.22160241e-04]
 [2.26996369e-03 4.60358925e-04 3.32040204e-03 1.60132723e-04]
 [2.79984524e-03 3.77386054e-04 3.35733802e-03 1.99709904e-04]
 [3.34934953e-03 3.16783996e-04 3.37131164e-03 2.39899797e-04]
 [3.91170305e-03 2.71162690e-04 3.37031899e-03 2.80096314e-04]
 [4.48261755e-03 2.35859375e-04 3.35938692e-03 3.19935345e-04]
 [5.05932348e-03 2.07875772e-04 3.34173124e-03 3.59198468e-04]
 [5.63998115e-03 1.85231587e-04 3.31946349e-03

In [11]:
print('\nlg K')
print(lg_k)

print('\nF_min')
print(F_min)

print('\nFinal enthalpies')
print(dH_res_out)

print('\ncalculated error of enthalpy')
print(disp)

if len(tar_num) > 0:
    print('\ncalculated error of constant')
    print(errs_values)


lg K
[[0.        ]
 [0.        ]
 [3.50213623]
 [4.82928467]]

F_min
3.938043469325817e-09

Final enthalpies
[0.0 0.0 9.990968089318486 12.878265298386111]

calculated error of enthalpy
[0.00079711 0.00679208]

calculated error of constant
[0.00119167 0.00132428]


In [12]:
#import matplotlib.pyplot

#s = 4.5

#xxx = []
#FFF = []
#while s < 5.5:
    #lg_k[tar_num] = s
    
    #c_res_out = eq_calc(max_iter, eps, ser_num, st_coeff_matrix, type_con, lg_k,
        #con_matrix, ign_indices, ser_counts, ser_info)
        
    #F_min, dH_res_out = enthalpies(ser_num, ser_counts, c_res_out, devs, volumes, heats, dH_ind, dH_par, dH_ind_wtf, 
                               #_calor_setup_type_coeff)
    
    #xxx.append(s)
    #FFF.append(F_min)
    #s += 0.02


#matplotlib.pyplot.plot(xxx, FFF, 'ro-')

#import sys
#import os
##sys.path.append('../kev_calorim')
#print(os.path.abspath('../kev/'))
#print(os.getcwd())

#lg_k is array

In [13]:
import matplotlib.pyplot as plt
from copy import copy, deepcopy

def risovalka(max_iter, eps, st_coeff_matrix, type_con, lg_k, con_matrix, ign_indices, ser_num, ser_counts, c_res_out, devs, volumes, heats, dH_ind, dH_par, dH_ind_wtf, 
                               _calor_setup_type_coeff, _calor_setup_type):

    s = [[0] * 42 for i in range(42)]
    const_x = [0] * 42
    const_y = [0] * 42
    s = np.array(s)

    i, a = 2.5, 0

    for counter_x in range(len(s)):
        j = 3.3
        const_x[counter_x] = round(i, 2)
        for counter_y in range(len(s)):
            lg_k[2], lg_k[3] = np.array(i), np.array(j)
            const_y[counter_y] = round(j, 2)
            c_res_out, g_res_out = eq_evaluator.eq_calc(max_iter, eps, st_coeff_matrix, type_con, lg_k,
                                                            con_matrix, ign_indices)
        
            F_min, dH_res_out, disp = cl_enthalpies(ser_num, ser_counts, c_res_out, devs, volumes, heats, dH_ind, dH_par, dH_ind_wtf, 
                                                       _calor_setup_type_coeff, _calor_setup_type)
            
            s[counter_x, counter_y] = float(F_min * 100000000)
        
            j += 0.05
    
        i += 0.05

    s = pd.DataFrame(data = s, index = const_y, columns = const_x)

    fig, ax = plt.subplots(figsize=(20, 20))
    im = ax.imshow(s, cmap = 'RdYlGn_r')
    ax.set_xticks(np.arange(len(const_x)))
    ax.set_yticks(np.arange(len(const_y)))

    ax.set_xlabel('lg K1')
    ax.set_ylabel('lg K2')

    ax.set_xticklabels(const_x)
    ax.set_yticklabels(const_y)

    plt.show()
    return s

In [14]:
#comment this section for reducing the waiting time
#s = risovalka(max_iter, eps, st_coeff_matrix, type_con, lg_k, con_matrix, ign_indices, ser_num, ser_counts, c_res_out, devs, volumes, heats, dH_ind, dH_par, dH_ind_wtf, 
                               #_calor_setup_type_coeff, _calor_setup_type)
#with pd.ExcelWriter('d:/KEVreplica/output/calorimetry/test_6.xlsx', mode = "w") as output:
    #s.to_excel(output)

In [15]:
F_min, dH_res_out, disp = cl_enthalpies(ser_num, ser_counts, c_res_out, devs, volumes, heats, dH_ind, dH_par, dH_ind_wtf, 
                                                       _calor_setup_type_coeff, _calor_setup_type) 


eq con
[[2.39381965e-17 1.00000000e-03 7.60618042e-17 3.86837491e-32]
 [5.64842374e-05 3.38508086e-03 6.07535293e-04 7.29070102e-07]
 [1.33786787e-04 2.79513196e-03 1.18820325e-03 3.37733756e-06]
 [2.42745449e-04 2.24195334e-03 1.72923040e-03 8.91814369e-06]
 [3.99373570e-04 1.74296271e-03 2.21178349e-03 1.87668956e-05]
 [6.23262314e-04 1.31941614e-03 2.61293049e-03 3.45994529e-05]
 [9.29314965e-04 9.87353310e-04 2.91548434e-03 5.75630970e-05]
 [1.31691730e-03 7.45806333e-04 3.12075565e-03 8.73149837e-05]
 [1.77037135e-03 5.77371619e-04 3.24784279e-03 1.22160241e-04]
 [2.26996369e-03 4.60358925e-04 3.32040204e-03 1.60132723e-04]
 [2.79984524e-03 3.77386054e-04 3.35733802e-03 1.99709904e-04]
 [3.34934953e-03 3.16783996e-04 3.37131164e-03 2.39899797e-04]
 [3.91170305e-03 2.71162690e-04 3.37031899e-03 2.80096314e-04]
 [4.48261755e-03 2.35859375e-04 3.35938692e-03 3.19935345e-04]
 [5.05932348e-03 2.07875772e-04 3.34173124e-03 3.59198468e-04]
 [5.63998115e-03 1.85231587e-04 3.31946349e-03 